# Generated by Django 5.1.3 on 2025-02-03 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_booking_closeddays_openinghours_delete_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Bookingmodel',
        ),
    ]
