# Generated by Django 5.1.3 on 2025-02-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='openinghours',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
