# Generated by Django 5.1.3 on 2025-02-03 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_openinghours_is_open_alter_openinghours_close_time_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpeningHours',
            new_name='opening_hours_list',
        ),
    ]
