# Generated by Django 5.1.3 on 2025-02-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_openinghours_delete_opening_hours_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghours',
            name='closing_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='opening_time',
            field=models.TimeField(),
        ),
    ]
