# Generated by Django 5.1.3 on 2025-02-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_openinghours_closing_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openinghours',
            options={'verbose_name': 'Opening Hour', 'verbose_name_plural': 'Opening Hours'},
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='closing_time',
            field=models.CharField(blank=True, choices=[('17:00', '5:00 PM'), ('18:00', '6:00 PM'), ('21:00', '9:00 PM')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='opening_time',
            field=models.CharField(blank=True, choices=[('09:00', '9:00 AM'), ('10:00', '10:00 AM')], max_length=5, null=True),
        ),
    ]
