# Generated by Django 5.1.3 on 2025-02-05 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_openinghours_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openinghours',
            options={},
        ),
    ]
